spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost/doctor"
    username: "dorian"
    password: "dorian01"
app:
  secret: "dfdfdfdjfefehjfekjfdw3435"
  issuer: "dorian"
jwt:
  private:
    key: classpath:private-key.pem
  public:
    key: classpath:public-key.pem



